In [22]:
import pandas as pd
import spacy
nlp = spacy.load('en')
doc1 = nlp(u'Hello hi there!')
doc2 = nlp(u'Hello hi there!')
doc3 = nlp(u'Hey whatsup?')

print(doc1.similarity(doc2)) # 0.999999954642
print(doc2.similarity(doc3)) # 0.699032527716
print(doc1.similarity(doc3)) # 0.699032527716

1.0
0.4591097084890523
0.4591097084890523

In [23]:
reviews = pd.read_csv("reviews_cleaned.csv")

/home/varun/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,2,4,5,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [24]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments,sentiment,subjectivity,comments_cleaned
0,1419,38924112.0,2015-07-19,11308465.0,Marcela,Having the opportunity of arriving to Alexandr...,0.410104,0.699479,opportunity arriving alexandra house describes...
1,1419,44791978.0,2015-08-29,9580285.0,Marco,We have no enough words to describe how beauty...,0.266667,0.683333,enough word describe beautyful cozy alexandra ...
2,1419,45957133.0,2015-09-07,38394721.0,Andrea,The listing was exceptional and an even better...,0.576111,0.717361,listing exceptional even better experience per...
3,1419,67295154.0,2016-03-28,3515044.0,Shaun,Alexandra's home was amazing and in such a nea...,0.295000,0.563333,alexandra home amazing neat neighbourhood ever...
4,1419,177702208.0,2017-08-03,13987100.0,Kate,Beautiful home. Very comfortable and clean. Pe...,0.502963,0.740000,beautiful home comfortable clean perfect famil...

In [ ]:
import pandas as pd
import spacy
nlp = spacy.load('en')

In [49]:
with open("comparison.txt", "w") as fp:
    for i in reviews.iloc.index:        
        doc_i = nlp(reviews.iloc[i]["comments_cleaned"])
        for j in reviews.iloc.index:
            doc_j = nlp(reviews.iloc[j]["comments_cleaned"])
            txt = str(i) + "," + str(j) + "," + str(doc_i.similarity(doc_j))               
            fp.write(txt + "\n")

In [50]:
#for line in open("comparison.txt", "r").readlines():
#    print(line.strip())

0,0,1.0
0,1,0.9322962469820303
0,2,0.9351619645877185
0,3,0.931980424056441
0,4,0.9457770856037455
0,5,0.8983453286285066
0,6,0.774342322605749
0,7,0.955769060101459
0,8,0.9206161825349831
0,9,0.9387266085199445
1,0,0.9322962469820303
1,1,1.0
1,2,0.9248928814559103
1,3,0.9361489271338228
1,4,0.8943490907972101
1,5,0.8896654313126603
1,6,0.8584181053543458
1,7,0.9397531684109057
1,8,0.856684659048341
1,9,0.9039336799839572
2,0,0.9351619645877185
2,1,0.9248928814559103
2,2,1.0
2,3,0.9468651897736103
2,4,0.9186891858312285
2,5,0.8983079273151944
2,6,0.8281553516632253
2,7,0.9053688358361274
2,8,0.8752060379197086
2,9,0.9240489235982859
3,0,0.931980424056441
3,1,0.9361489271338228
3,2,0.9468651897736103
3,3,1.0
3,4,0.8945561129141666
3,5,0.8501634134666859
3,6,0.79803665970232
3,7,0.9391779428092488
3,8,0.8836415483302001
3,9,0.9222132445147329
4,0,0.9457770856037455
4,1,0.8943490907972101
4,2,0.9186891858312285
4,3,0.8945561129141666
4,4,1.0
4,5,0.8877890749152286
4,6,0.7558290273660287
4,7,0.9206580768133552
4,8,0.9029895008404153
4,9,0.9116000223809763
5,0,0.8983453286285066
5,1,0.8896654313126603
5,2,0.8983079273151944
5,3,0.8501634134666859
5,4,0.8877890749152286
5,5,1.0
5,6,0.7769553691418367
5,7,0.8752526355047232
5,8,0.8632348356830877
5,9,0.8898387432600918
6,0,0.774342322605749
6,1,0.8584181053543458
6,2,0.8281553516632253
6,3,0.79803665970232
6,4,0.7558290273660287
6,5,0.7769553691418367
6,6,1.0
6,7,0.7588790981221202
6,8,0.7135258047581249
6,9,0.7551061941938109
7,0,0.955769060101459
7,1,0.9397531684109057
7,2,0.9053688358361274
7,3,0.9391779428092488
7,4,0.9206580768133552
7,5,0.8752526355047232
7,6,0.7588790981221202
7,7,1.0
7,8,0.9066434682731311
7,9,0.9428043830812617
8,0,0.9206161825349831
8,1,0.856684659048341
8,2,0.8752060379197086
8,3,0.8836415483302001
8,4,0.9029895008404153
8,5,0.8632348356830877
8,6,0.7135258047581249
8,7,0.9066434682731311
8,8,1.0
8,9,0.9285100978851805
9,0,0.9387266085199445
9,1,0.9039336799839572
9,2,0.9240489235982859
9,3,0.9222132445147329
9,4,0.9116000223809763
9,5,0.8898387432600918
9,6,0.7551061941938109
9,7,0.9428043830812617
9,8,0.9285100978851805
9,9,1.0